<?php
/**
 * LAYER 1 - creates / refreshes the plug-in's read-only MySQL account for this tenant.
 *
 *   php install/apply_grants.php <mysql-root-password> [root-user]
 *
 * The account (config 'aiAccounts'[tenant]) receives, and nothing else:
 *   - SELECT on each CATALOGUED table, restricted to its NON-SENSITIVE columns
 *     (column-level grants: passwords, bank accounts, NID, DOB... are simply not granted,
 *     so MySQL itself refuses them - even if the validator were bypassed);
 *   - SELECT on the chatbot's self-service / scoped v_* views.
 * No grant on logins, logs, credential stores, empty or backup tables, or any other object.
 * Writes the exact statements to data/grants.sql.php (password masked) for review.
 * Re-run after rebuilding the catalogue. Idempotent (drops and recreates the account).
 */

if (PHP_SAPI !== 'cli') { http_response_code(404); exit; } // command line only

require_once __DIR__ . '/../bootstrap.php';

use AiChatbot\Catalog;
use AiChatbot\Config;
use AiChatbot\Db;

$rootPassword = $argv[1] ?? '';
$rootUser = $argv[2] ?? 'root';
if ($rootPassword === '') {
    fwrite(STDERR, "usage: php install/apply_grants.php <mysql-root-password> [root-user]\n");
    exit(1);
}

Db::useAdminAccount();
$tenant = Db::tenant();
$account = Config::get('aiAccounts')[$tenant] ?? null;
if (!$account) {
    fwrite(STDERR, "No aiAccounts entry for tenant '$tenant' in config.local.php\n");
    exit(1);
}
$user = $account['username'];
$q = fn(string $id) => '`' . str_replace('`', '``', $id) . '`';

$statements = [];
foreach (['localhost', '127.0.0.1'] as $host) {
    $statements[] = "DROP USER IF EXISTS '$user'@'$host'";
    $statements[] = "CREATE USER '$user'@'$host' IDENTIFIED BY '__PASSWORD__' WITH MAX_USER_CONNECTIONS 20";
}
$tableCount = $columnCount = 0;
foreach (Catalog::tables() as $name => $t) {
    $cols = implode(', ', array_map($q, array_column($t['columns'], 'name')));
    foreach (['localhost', '127.0.0.1'] as $host) {
        $statements[] = "GRANT SELECT ($cols) ON {$q($tenant)}.{$q($name)} TO '$user'@'$host'";
    }
    $tableCount++;
    $columnCount += count($t['columns']);
}
foreach (array_keys(Catalog::VIEWS) as $view) {
    foreach (['localhost', '127.0.0.1'] as $host) {
        $statements[] = "GRANT SELECT ON {$q($tenant)}.{$q($view)} TO '$user'@'$host'";
    }
}

file_put_contents(AI_CHATBOT_DIR . '/data/grants.sql.php',
    AI_CHATBOT_FILE_GUARD . "-- Generated by install/apply_grants.php on " . date('c') . " for tenant $tenant (password masked)\n"
    . implode(";\n", $statements) . ";\n");

$root = new PDO(sprintf('mysql:host=%s;port=%d', Config::get('dbHost', 'localhost'), (int) Config::get('dbPort', 3306)),
    $rootUser, $rootPassword, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
foreach ($statements as $sql) {
    $root->exec(str_replace('__PASSWORD__', str_replace("'", "''", $account['password']), $sql));
}
$root->exec('FLUSH PRIVILEGES');

printf("'%s': SELECT on %d tables (%d non-sensitive columns) + %d views in %s; statements in data/grants.sql.php\n",
    $user, $tableCount, $columnCount, count(Catalog::VIEWS), $tenant);
